# Generated by Django 5.1.1 on 2024-09-23 23:04

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage',
            name='image',
            field=models.ImageField(upload_to='hero_images/', validators=[home.models.validate_image_extension]),
        ),
    ]
