# Generated by Django 5.1.1 on 2024-09-22 13:43

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[products.models.validate_image_extension]),
        ),
    ]
