# Generated by Django 5.1.1 on 2024-09-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_remove_product_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='armpit_to_armpit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_info',
            field=models.CharField(default='No Info', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shoulders',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sleeve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_size',
            field=models.CharField(choices=[('No Info', 'No Info'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L')], default='No Info', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='waist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
