# Generated by Django 5.1.1 on 2024-09-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_armpit_to_armpit_product_fabric_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='armpit_to_armpit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fabric_info',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shoulders',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sleeve',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='waist',
        ),
    ]
