# Generated by Django 4.2.13 on 2025-01-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_armpit_to_armpit_product_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
